name: TF-Deploy EKS cluster on AWS

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      - name: Terraform Init 
        env:
          BACKEND_CONFIG: ../config.academy.s3.tfbackend
        run : |         
           cd terraform/eks-cluster
           terraform init -backend-config=$BACKEND_CONFIG
      - name: Terraform Validate
        run : |         
           cd terraform/eks-cluster
           terraform validate
      - name: Terraform Plan
        run : |         
           cd terraform/eks-cluster
           terraform plan
      - name: Terraform Apply      
        if: env.TF_STEP_BY_STEP == 'apply'
        run : |         
           cd terraform/eks-cluster
           terraform apply --auto-approve
      - name: Terraform Destroy
        if: env.TF_STEP_BY_STEP == 'destroy'
        run : |         
           cd terraform/eks-cluster
           terraform apply -destroy --auto-approve
           