name: TF-Deploy Hello-VPC infra on AWS

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      - name: Terraforming
        env:
          BACKEND_CONFIG: ../config.academy.s3.tfbackend
        run : |         
           cd terraform/hello-infra
           terraform init -backend-config=$BACKEND_CONFIG
           terraform validate
           terraform plan
            terraform apply --auto-approve
            terraform apply -destroy --auto-approve